export type ProjectSection = {
  heading: string;
  body: string;
};

export type Project = {
  slug: string;
  name: string;
  category: string;
  summary: string;
  cover: string;
  stack: string[];
  github?: string;
  demo?: string;
  featured: boolean;
  sections: ProjectSection[];
};

export const featuredProjects: Project[] = [
  {
    slug: "zyviora",
    name: "Zyviora",
    category: "Hybrid AI Companion",
    summary:
      "A hybrid AI companion combining LLM reasoning with symbolic logic for persistent memory, mood tracking, and voice interaction.",
    cover: "/images/zyviora-cover.png",
    stack: [
      "Python",
      "Flask",
      "Google Gemini API",
      "Prolog",
      "PySwip",
      "SQLite",
      "JavaScript",
      "Chart.js",
    ],
    github: "https://github.com/Susmitha-Peravali/Zyviora_Personal_Companion",
    demo: "https://zyviora-personal-companion.onrender.com",
    featured: true,
    sections: [
      {
        heading: "Overview",
        body: "Zyviora pairs a large language model with a Prolog-based symbolic reasoning layer, giving the assistant both fluent conversation and consistent, rule-based memory of the user over time.",
      },
      {
        heading: "Problem",
        body: "Most conversational AI companions either forget context between sessions or hallucinate facts about the user because memory lives only in a prompt window, not in a structured store.",
      },
      {
        heading: "Solution",
        body: "A hybrid architecture: the Gemini API handles natural language understanding and generation, while a PySwip-driven Prolog knowledge base stores facts, mood history, and reminders as queryable logic — giving the assistant persistent, verifiable memory.",
      },
      {
        heading: "Architecture",
        body: "Voice input is transcribed and routed to the LLM for intent parsing. Extracted facts and intents are asserted into the Prolog knowledge base. Responses are generated by combining LLM output with facts queried back from Prolog, keeping the model grounded in what it actually knows about the user.",
      },
      {
        heading: "Features",
        body: "Voice assistant interaction, mood tracking over time, a reminder system, an AI chat interface, and a dashboard for reviewing history and insights.",
      },
      {
        heading: "Challenges",
        body: "The hardest part was keeping the LLM and the symbolic layer in sync — deciding what belongs in fast, fuzzy language understanding versus what must be asserted as a hard fact in Prolog.",
      },
      {
        heading: "Lessons Learned",
        body: "Symbolic reasoning is a strong complement to LLMs specifically where correctness and persistence matter more than fluency — memory and rules are a good fit for logic programming, not just prompting.",
      },
      {
        heading: "Future Improvements",
        body: "Multi-user support, richer emotional modeling, and a lighter-weight local fallback for offline voice interaction.",
      },
    ],
  },
  {
    slug: "tech-resale-hub",
    name: "Tech Resale Hub",
    category: "Marketplace Platform",
    summary:
      "A real-time marketplace for buying and selling used tech, with role-based flows for buyers, sellers, and admins.",
    cover: "/images/resale-cover.jpeg",
    stack: ["React", "Node.js", "Express.js", "MongoDB", "Socket.io", "JWT", "RBAC", "REST APIs"],
    github: "https://github.com/Susmitha-Peravali/Tech_Resale_Hub",
    featured: true,
    sections: [
      {
        heading: "Overview",
        body: "Tech Resale Hub is a marketplace platform connecting buyers and sellers of used electronics, with real-time chat and role-specific dashboards.",
      },
      {
        heading: "Problem",
        body: "Casual resale of used tech tends to happen across disconnected channels — chat apps, classifieds, forums — with no trust layer or transaction history.",
      },
      {
        heading: "Solution",
        body: "A single platform with authenticated buyer, seller, and admin roles, built-in real-time chat for negotiation, and a moderated listing flow.",
      },
      {
        heading: "Architecture",
        body: "An Express REST API backed by MongoDB handles listings, users, and transactions. JWT secures role-based routes. Socket.io powers real-time chat between buyers and sellers, with presence and message delivery handled server-side.",
      },
      {
        heading: "Features",
        body: "Real-time buyer-seller chat, role-based dashboards, listing management, and an admin moderation view.",
      },
      {
        heading: "Challenges",
        body: "Keeping chat state consistent across reconnects and multiple browser tabs required careful handling of Socket.io rooms and session identity.",
      },
      {
        heading: "Lessons Learned",
        body: "Real-time features change how you think about state — server-authoritative state with optimistic UI updates was far more reliable than trusting the client.",
      },
      {
        heading: "Future Improvements",
        body: "Escrow-style payment handling, seller ratings, and image-based listing search.",
      },
    ],
  },
  {
    slug: "bizvaani",
    name: "BizVaani",
    category: "Voice-First Retail Operating System",
    summary:
      "A voice-first operating system for retail businesses, with responsive dashboards for inventory and sales.",
    cover: "/images/bizvaani-cover.svg",
    stack: ["React", "Next.js", "Tailwind CSS", "Voice UI", "JWT"],
    github: "https://github.com/pankajydv07/BizVaani",
    demo: "https://biz-vaani.vercel.app",
    featured: true,
    sections: [
      {
        heading: "Overview",
        body: "BizVaani is a voice-first retail operating system that lets small business owners manage inventory and sales by speaking, rather than navigating dense forms.",
      },
      {
        heading: "Problem",
        body: "Many small retail owners find traditional dashboard software slow to use during busy hours — every action requires screen time they don't have on the shop floor.",
      },
      {
        heading: "Solution",
        body: "A voice-first interface layered over a conventional dashboard, so common actions — checking stock, logging a sale — can happen by voice while the dashboard remains available for deeper review.",
      },
      {
        heading: "Architecture",
        body: "A Next.js frontend renders responsive dashboards; voice input is captured and parsed into structured commands that map to the same API actions available through the UI, keeping voice and manual flows consistent.",
      },
      {
        heading: "Features",
        body: "Voice-first UI, responsive inventory and sales dashboards, and API-driven data sync.",
      },
      {
        heading: "Challenges",
        body: "Designing a voice command grammar flexible enough for natural phrasing but constrained enough to map reliably to actions.",
      },
      {
        heading: "Lessons Learned",
        body: "Voice interfaces need the same information architecture discipline as visual ones — a clear model of what a user can 'say' at any point.",
      },
      {
        heading: "Future Improvements",
        body: "Multi-language voice support and offline-first inventory sync.",
      },
    ],
  },
];

export const otherProjects = [
  {
    name: "Employee Burnout Prediction",
    description: "A machine learning model predicting employee burnout risk from workplace data.",
    stack: ["Python", "Machine Learning"],
  },
  {
    name: "Mini E-Commerce Store",
    description: "A compact full-stack e-commerce store with cart, checkout, and admin flows.",
    stack: ["React", "Node.js"],
  },
  {
    name: "Desktop Voice Assistant",
    description: "A desktop voice assistant for everyday task automation.",
    stack: ["Python"],
  },
  {
    name: "Line Follower Robot",
    description: "An autonomous line-following robot built as part of a robotics minor project.",
    stack: ["C++", "Robotics"],
  },
  {
    name: "Skill Exchange Platform",
    description: "A platform for peer-to-peer skill exchange and scheduling.",
    stack: ["React", "Node.js", "MongoDB"],
  },
];
